
---
- name: Building Tendermint Docker
  docker_image:
    name: "{{ tendermint_image_name }}"
    state: build
    tag: "{{tendermint_image_tag }}"
    build:
      dockerfile: Dockerfile
      path: "{{ home_dir }}/pkg/configuration/roles/tendermint/files"
      args:
        tm_version: "v{{ tm_version }}"
      nocache: yes
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [tendermint]

- name: Configuring Tendermint Containers
  docker_container:
    name: "tm_config_gen"
    image: "{{ tendermint_image_name }}:{{ tendermint_image_tag }}"
    detach: true
    env:
      STACK_SIZE: "{{ stack_size }}"
      TM_DOCKER_NAME: "{{ tendermint_docker_name }}"
    volumes:
      - "{{ tendermint_host_mount_config_dir }}{{ tendermint_home }}:{{ tendermint_home }}"
      - "../scripts:/scripts"
    entrypoint: ''
    command: /usr/bin/env bash -c "/scripts/tm_config_gen"
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [tendermint]

- name: Starting Tendermint Containers
  docker_container:
    name: "{{ tendermint_docker_name }}{{ item }}"
    hostname: "{{ tendermint_docker_name }}{{ item }}"
    image: "{{ tendermint_image_name }}:{{ tendermint_image_tag }}"
    detach: true
    network_mode: bridge
    networks:
      - name: "{{ bigchaindb_docker_net }}"
    published_ports:
      - "{{ tendermint_p2p_port }}"
      - "{{ tendermint_rpc_port }}"
    volumes:
      - "{{ tendermint_host_mount_dir }}{{ item|string }}{{ tendermint_home }}:{{ tendermint_home }}"
      - "{{ tendermint_host_mount_dir }}{{ item|string }}{{ tendermint_data }}:{{ tendermint_data }}"
      - "{{ tendermint_host_mount_config_dir }}{{ tendermint_home }}:/tendermint_config"
      - "../scripts:/scripts"
    entrypoint: ''
    command: bash -c "/scripts/tm_start"
    env:
      STACK_SIZE: "{{ stack_size|string }}"
      TM_DOCKER_NAME: "{{ tendermint_docker_name|string }}"
      TM_P2P_PORT: "{{ tendermint_p2p_port|string }}"
      BIGCHAINDB_DOCKER_NAME: "{{ bigchaindb_docker_name|string }}"
      _ITEM: "{{ item|string }}"
    state: started
    keep_volumes: true
  with_sequence: start=1 end="{{ stack_size|int }}" stride=1
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [tendermint]


