---
stack_type: "local"
stack_size: "4"
stack_box_name: "bento/ubuntu-18.04"
stack_type_provider: ""
stack_vm_memory: "512"
stack_vm_cpus: "1"
tm_version: "0.31.5"
mongo_version: "3.6"
ssh_private_key_path: ""
