# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---

# - name: Add MongoDB APT Key from KeyServer
#   apt_key:
#     keyserver: hkp://keyserver.ubuntu.com:80
#     id: EA312927

# - name: Add MongoDB to APT Sources
#   lineinfile:
#     dest: /etc/apt/sources.list.d/mongodb-org-4.2.list
#     regexp: "^deb(\\s+)http://repo.mongodb.org/apt/"
#     line: "{{ mongodb_apt_repo }}"
#     state: present
#     create: yes
#     mode: 0644

# - name: "apt-get update"
#   apt: update_cache=yes upgrade=safe cache_valid_time=3600


# - name: Install MongoDB
#   apt: name="mongodb-org" state=present

# - name: Register MongoDB as Service
#   become: yes
#   become_user: root
#   copy:
#     src: mongodb.service
#     dest: /etc/systemd/system/mongodb.service
#     owner: root
#     group: root
#     mode: 0644

# - name: Restart MongoDB Service
#   become: yes
#   become_user: root
#   service: name=mongodb state=restarted

# - name: Enable MongoDB Service
#   become: yes
#   become_user: root
#   service: name=mongodb enabled=yes

- name: Install mongodb
  apt: name="mongodb" state=present

- name: "apt-get update"
  apt: update_cache=no

- name: Enable mongodb service
  shell: "systemctl enable mongodb"

- name: restart mongodb
  shell: "systemctl restart mongodb"



