
---
- name: Running MongoDB Docker
  docker_container:
    name: "{{ mongodb_docker_name }}{{ item }}"
    hostname: "{{ mongodb_docker_name }}{{ item }}"
    image: "mongo:{{ mongo_version }}"
    detach: true
    network_mode: bridge
    networks:
      - name: "{{ bigchaindb_docker_net }}"
    published_ports:
      - "{{ mongodb_port }}"
    restart_policy: always
    volumes:
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/db:{{ mongodb_storage_path }}"
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/configdb:{{ mongodb_config_path }}"
    state: started
    keep_volumes: true
    command: mongod
  with_sequence: start=1 end="{{ stack_size|int }}" stride=1
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [mongodb]

