---

- name: Install python
  apt:
    name: ['python3.6','python3-pip' ]
    allow_unauthenticated: true
  register: install_python_res
  become: yes

- name: Configure python for bigchaindb user
  shell: |
    bash << EOF
    PYTHON_BIN=\$(which python3.6)
    PYTHON_BIN_DIR=\$(dirname \$PYTHON_BIN)
    mkdir -p ~/bin
    ln -sfn \$PYTHON_BIN ~/bin/python3
    ln -sfn \$PYTHON_BIN ~/bin/python
    if [[ \$PATH != \$HOME/bin* ]]; then
        echo 'export PATH="\$HOME/bin:\$PATH"' >> ~/.profile;
    fi
    EOF

- name: Install setuptools
  shell: "pip3 install -U pip setuptools"


- name: Install pip wheel
  pip:
    name: ['wheel']
    state: latest
    executable: pip3

